name: teamapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_lints: ^6.0.0
  provider: ^6.1.5+1
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0
  firebase_database: ^12.0.2
  url_launcher: ^6.3.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  flutter_chat_bubble: ^2.0.2
  fluttertoast: ^9.0.0
  file_picker: ^10.3.3
  animated_text_kit: ^4.3.0
  animated_theme_switcher: ^2.0.10
  flutter_countdown_timer: ^4.1.0
  flutter_pdfview: ^1.4.3
  cached_network_image: ^3.4.1
  firebase_ui_auth: ^3.0.0
  image_picker_web: ^4.0.0
  firebase_storage: ^13.0.2
  hooks_riverpod: ^3.0.3
  flutter_hooks: ^0.21.3+1
  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.2
  flutter_neumorphic: ^3.2.0
  path_provider: ^2.1.5
  html: ^0.15.6
  dashboard: ^0.0.4
  flutter_bloc: ^9.1.1
  geolocator: ^14.0.2
  webview_flutter: ^4.13.0
  font_awesome_flutter: ^10.10.0
  sqflite: ^2.4.2
  fl_chart: ^1.1.1
  photo_view: ^0.15.0
  camera: ^0.11.2
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.2.1
  percent_indicator: ^4.2.5
  flutter_rating_bar: ^4.0.1
  settings_ui: ^2.0.2
  auto_size_text: ^3.0.0
  flutter_slidable: ^4.0.3
  firebase_analytics: ^12.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  badges: ^3.1.2
  feedback: ^3.2.0
  chart_components: ^1.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_form_builder: ^10.2.0
  animations: ^2.0.11
  dropdown_search: ^6.0.2
  local_auth: ^2.3.0
  flutter_xlider: ^3.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter_icons:
  android: true
  ios: true
  image_path: "assets/finallogo.png"

flutter:
  assets:
    - assets/

  uses-material-design: true
