name: teamapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_lints: ^3.0.1
  provider: ^6.1.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_database: ^10.4.11
  url_launcher: ^6.2.5
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  flutter_chat_bubble: ^2.0.2
  fluttertoast: ^8.2.4
  file_picker: ^6.2.0
  animated_text_kit: ^4.2.2
  animated_theme_switcher: ^2.0.10
  flutter_countdown_timer: ^4.1.0
  flutter_pdfview: ^1.3.2
  cached_network_image: ^3.3.1
  firebase_ui_auth: ^1.13.1
  image_picker_web: ^3.1.1
  firebase_storage: ^11.6.11
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.1.1
  flutter_neumorphic: ^3.2.0
  path_provider: ^2.1.2
  html: ^0.15.4
  dashboard: ^0.0.4
  flutter_bloc: ^8.1.5
  geolocator: ^11.0.0
  webview_flutter: ^4.7.0
  font_awesome_flutter: ^10.7.0
  sqflite: ^2.3.2
  fl_chart: ^0.67.0
  photo_view: ^0.14.0
  camera: ^0.10.5+9
  flutter_staggered_grid_view: ^0.7.0
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.2.3
  flutter_rating_bar: ^4.0.1
  settings_ui: ^2.0.2
  auto_size_text: ^3.0.0
  flutter_slidable: ^3.1.0
  firebase_analytics: ^10.9.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  badges: ^3.1.2
  feedback: ^3.0.1
  chart_components: ^1.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_form_builder: ^9.2.1
  animations: ^2.0.11
  dropdown_search: ^5.0.6
  local_auth: ^2.2.0
  flutter_xlider: ^3.5.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_icons:
  android: true
  ios: true
  image_path: "assets/finallogo.png"

flutter:
  assets:
    - assets/hsnc_logo.png
    - assets/instagram_icon.png
    - assets/img1.png
    - assets/logo.png
    - assets/sportsday.jpg
    - assets/finallogo.png
    - assets/xaviers.png
    - assets/wilson.png

  uses-material-design: true
