// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB06F9fc9k3_OYBO5xPAHLTEBD-WYyJsY',
    appId: '1:881093348947:web:a0b74e0b193a2afb3980a6',
    messagingSenderId: '881093348947',
    projectId: 'teamapp-da9d9',
    authDomain: 'teamapp-da9d9.firebaseapp.com',
    databaseURL: 'https://teamapp-da9d9-default-rtdb.firebaseio.com',
    storageBucket: 'teamapp-da9d9.appspot.com',
    measurementId: 'G-ZMZC6X34DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOhEpO-i0HvCHnh6k1GcRqmhqW4_7SyE8',
    appId: '1:881093348947:android:8392bb808757421b3980a6',
    messagingSenderId: '881093348947',
    projectId: 'teamapp-da9d9',
    databaseURL: 'https://teamapp-da9d9-default-rtdb.firebaseio.com',
    storageBucket: 'teamapp-da9d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbfTZDeuLSbrOXuQIhE0NZqbLNpjsSVyU',
    appId: '1:881093348947:ios:869a71f35f74185c3980a6',
    messagingSenderId: '881093348947',
    projectId: 'teamapp-da9d9',
    databaseURL: 'https://teamapp-da9d9-default-rtdb.firebaseio.com',
    storageBucket: 'teamapp-da9d9.appspot.com',
    iosBundleId: 'com.example.teamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbfTZDeuLSbrOXuQIhE0NZqbLNpjsSVyU',
    appId: '1:881093348947:ios:f9e165e20fbae93a3980a6',
    messagingSenderId: '881093348947',
    projectId: 'teamapp-da9d9',
    databaseURL: 'https://teamapp-da9d9-default-rtdb.firebaseio.com',
    storageBucket: 'teamapp-da9d9.appspot.com',
    iosBundleId: 'com.example.teamApp.RunnerTests',
  );
}
